[project]
name = "youtube-ai-transcript"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ollama>=0.4.5",
    "streamlit>=1.41.1",
    "youtube-transcript-api>=0.6.3",
]
